language: rust
rust:
- nightly
- beta
- stable
addons:
  apt:
    packages:
    - libgtk-3-dev
    - python3
env:
  - GTK=3.4
  - GTK=latest
script:
  - rm -rf sys/gtk-sys
  - ./cargo-fixup.py
  - cd examples
  - ./build.sh
