language: rust
rust:
- nightly
- beta
- stable
addons:
  apt:
    packages:
    - libgtk-3-dev
    - python3
env:
  - GTK=3.4
  - GTK=3.18
script:
  - ./crates.py checkout crates.txt build
  - cd build
  - ../cargo-fixup.py
  - cd examples
  - ./build.sh
  - cd ../gtk
  - if [ "$GTK" = 3.4 ]; then cargo test --features embed-lgpl-docs; fi
  - if [ "$GTK" = 3.18 ]; then PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig" cargo test --features "v3_16 embed-lgpl-docs"; fi
